### ISSUE TITLE
Downstream minigbm frontend -> gbm backend maintaining

### ISSUE THREAD

**Issue by rsglobal** [aosp-developers-community/aosp-developers-community.github.io#5]
@johnstultz-work @superna9999 @joe-skb7 @MarijnS95 @makohoek 

Hi guys,

I would like to add minigbm fork with my gbm_mesa (and dmabuf_heaps) backend , which is successor of gbm_gralloc project.
The final goal is merging with minigbm, but at this moment we need a place where community can collaborate on/test it.

Any objections?

**Comment by kcxt** [comment]
+1 from me

**Comment by MarijnS95** [comment]
Sounds good, I take it upstream isn't allowing you to have a development branch within the official repo?

Will you add it here under @aosp-developers-community or under @aospm?

**Comment by rsglobal** [comment]
Official repo is chromium os gerrit, I doubt I could negotiate something like that with CrOS management.

I plan to add repository here.

**Comment by MarijnS95** [comment]
Worth a shot?

> I plan to add repository here.

Alright, just realizing that this GH organization has a few more members but no repos, @aospm has a bunch of repos and actual device support but fewer members. I'm not seeing why we have/need both. Different stakeholders?

**Comment by rsglobal** [comment]
aospm is already bloated with a lot of repositories

I would like to see a place where only generic HALs will be maintained (in a case such HALS doesn't have another home).
So I hope we can carefully create such a place here.

I will create sandbox repository here, which, I hope, will be used as an entry-point for such HALs.

**Comment by rsglobal** [comment]
https://github.com/aosp-developers-community/sandbox/pull/2
